-- ------------- FUNCIONALIDADES. ----------------
-- FACTURACION
-- 1. SI EXISTE EL CLIENTE EN LA BD LO SUGIERE 
-- 2. SI NO EXISTE EL CLIENTE EN LA BD LO CREA 
-- 3. AL OBTENER LA SUGERENCIA DEL CLIENTE SE PUEDE EDITAR SUS CAMPOS A EXCEPCION DE LA IDENTIFICACION Y LO EDITARA EN LA BD
-- 4. SUGERENCIA DE LOS PRODUCTOS REGISTRADOS EN LA BD
-- 5. SE PUEDE MODIFICAR LOS CAMPOS DEL PRODUCTO QUE FUERON SUGERIDOS A EXCEPCION DEL NOMBRE
-- 6. AGREGA EL PRODUCTO SELECCIONADO EN LA TABLA (ESTO SE PUEDE REPETIR VARIAS VECES PARA TENER MULTIPLES PRODUCTOS)
-- 7. BOTON DE IMPRIMIR POS, ESTE BOTON IMPRIMIRA LA FACTURA EN FORMATO POS
-- 8. BOTON DE GUARDAR FACTURA EN PDF, ESTE BOTON GUARDARA UN DOCUMENTO PDF
-- 9. BOTON DE LIMPIAR -> LIMPIA LOS DATOS DEL PRODUCTO
-- 10. BOTON DE CANCELAR -> LIMPIA TODOS LOS DATOS DE LA FACTURA -> DATOS DE CLIENTE, PRODUCTO Y PRODUCTOS REGISTRADOS EN LA TABLA
-- 11. AL GUARDAR LA FACTURA CON CUALQUIER OPCION SE REGISTRARA LA VENTA EN LA BASE DE DATOS CON DATOS DE CLIENTE Y PRODUCTOS 
-- 12. MENSAJE PERSONALIZADO EN LA FACTURA DE GARANTIA, TOMARA EL MENSAJE DEL CAMPO DE CATEGORIA DE GARANTIA Y LO PONE EN LA FACTURA PARA TENER EN CUENTA LOS DETALLES PARA CUMPLIR CON LA GARANTIA DE LA CATEGORIA COMPRADA
-- 13. MENSAJES DE VALIDACION
-- 14. SI TENEMOS ESCRITO UN PRODUCTO Y NO LO AGREGAMOS A LA TABLA SALDRA UN MENSAJE SI DESEAMOS DESCARTARLO O NO
-- 15. AL COMPRAR LA CANTIDAD MAXIMA DEL PRODUDCTO YA NO SALDRA EN LAS SUGERENCIAS Y SE PONDRA COMO AGOTADO
-- 16. AL INTENTAR COMPRAR MAS DE LA CUENTA NOS DARA UN MENSAJE DE EL TOTAL DE DICHO PRODUCTO 

-- INVENTARIO
-- 1. BOTON DE AGREGAR CATEGORIA CON CAMPOS NOMBRE, DESCRIPCION DE CATEGORIA, Y MENSAJE DE GARANTIA
-- 2. BOTON DE AGREGAR PRODUCTO, AGREGA UN PRODUCTO CAMPOS (NOMBRE, PRECIO DE COMPRA, DE VENTA, CANTIDAD, CATEGORIA)
-- 3. BOTON DE VER TOTALES, MIRA EL TOTAL DE TODOS LOS PRODUCTOS
-- 4. BARRA DE BUSQUEDA, ESTA BUSCARA LOS PRODUCTOS
-- 5. OPTION DE CATEGORIA AL SELECCIONAR LA CATEGORIA NOS TRAERA TODOS LOS PRODUCTOS QUE SEAN DE LA CATEGORIA SELECCIONADA
-- 6. PAGINACION DE LOS PRODUCTOS
-- 7. ACCIONES EN LA TABLA POR CADA PRODUCTO, EL DE EDITAR PARA EDITAR Y AGOTAR PARA MARCARLO COMO AGOTADO
-- 8. BOTON DE PRODUCTOS INACTIVOS, EN ESTE PODREMOS MIRAR TODOS LOS PRODUCTOS AGOTADOS Y EDITARLOS
-- 9. SI UN PRODUCTO AGOTADO SE EDITA Y SE LE PONE CANTIDAD DE >= 1 SE PONDRA AUTOMATICAMENTE COMO DISPONIBLE

-- VENTAS
-- 1. EN LA TABLA PODEMOS REVISAR LAS VENTAS GENERADAS CON FACTURA ID, CLIENTE, CEDULANIT, FECHA, TOTAL Y EL BOTON DE VER DETALLES
-- 2. VER DETALLES SIRVE PARA MIRAR LOS DETALLES DE LA FACTURA, PRODUCTO, DESCRIPCION, CANTIDAD, GARANTIA, PRECIO DE COMPRA, PRECIO DE VENTA Y TOTAL


-- PEDIDOS
-- 1. SIRVE PARA REGISTRAR LOS PEDIDOS QUE AUN NO LLEGAN 
-- 2. BOTON DE AGREGAR PEDIDO CON MISMOS CAMPOS QUE PRODUCTO
-- 3. ACCIONES EN EL PEDIDO DE ELIMINAR PARA BORRARLO
-- 4. ACCION DE RECIBIDO, ESTE HARA QUE SE PASE DIRECTAMENTE A LA TABLA DE INVENTARIO DE PRODUCTOS
-- 5. MIRAR EL TOTAL DE LOS PEDIDOS

-- ACTIVOS (ACTIVOS DE EL NEGOCIO CON LOS CUALES SE TRABAJA O SE USA)
-- 1. BOTON DE AGREGAR ACTIVO CON CAMPO NOMBRE DEL ACTIVO, PRECIO DE COMPRA, CANTIDAD, TOTAL Y ACCIONES
-- 2. ACCION DE ELIMINAR ACTIVO
-- 3. ACCION DE EDITAR ACTIVO
-- 4. MIRAR EL TOTAL DE LOS ACTIVOS

-- CLIENTE
-- 1. TABLA EN DONDE MIRAREMOS LOS CLIENTES REGISTRADOS POR LA FACTURACION O CREADOS DIRECTAMENTE CON CAMPOS (ID, NOMBRE, IDENTIFICACION, TELEFONO, DIRECCION Y CORREO)
-- 2. BOTON DE AGREGAR CLIENTE PARA AGREGAR UNO NUEVO, OBLIGATORIO SIEMPRE SERA NOMBRE Y CEDULA Y DE RESTO OPCIONALES
-- 3. BOTON EN LA TABLA DE EDITAR CLIENTE PARA CADA UNO, Y AQUI PODREMOS EDITAR EL CLIENTE, A DIFERNCIA DE FACTURACION  QUE SE PUEDE MODIFICAR UN CLIENTE SIEMPRE Y CUANDO TENGA SU MISMA CEDULA ACA LE PODEMOS MODIFICAR LA CEDULA
-- 4. BOTON DE REVISAR CLIENTES TOP -> ESTE NOS DARA LOS CLIENTES EN TOP 10 QUE MAS HAN COMPRADO 